name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: python

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Cache pip
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.local/share/virtualenvs
          # Look to see if there is a cache hit for the corresponding requirements file
          # Working-directory does not work here in combination with "uses:"
          key: ${{ runner.os }}-pipenv-${{ hashFiles('python/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Lint with flake8
        run: |
          pipenv run flake8 .
      - name: Format check with Black
        run: |
          pipenv run black --check .
      - name: Test with pytest
        run: |
          pipenv run pytest --junitxml=junit/test-results.xml
